apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/argoproj/argo-cd/manifests/base?ref=v1.7.4
- routes/argocd_server_route.yaml
- serviceaccounts/argocd-manager.yaml
patchesStrategicMerge:
- services/argocd_metrics_service_patch.yaml
- services/argocd_server_metrics_service_patch.yaml
- deployments/argocd-repo-server_patch.yaml
- deployments/argocd-server_patch.yaml
- deployments/argocd-redis_patch.yaml
