apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-app-of-apps
spec:
  destination:
    namespace: argocd
    name: moc-infra
  project: operate-first
  source:
    path: envs/moc/zero
    repoURL: https://github.com/operate-first/argocd-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
