apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        image: quay.io/aicoe/argocd:v1.7.4-1
        env:
        - name: GNUPGHOME
          value: /home/argocd/.gnupg
        volumeMounts:
        - name: key
          mountPath: /key
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "gpg --import /key/private.key"]
      volumes:
      - name: key
        secret:
          secretName: ksops-pgp-key
